---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-9}-python-${PYTHON_VERSION:-3.11}"
    hostname: python
    image: "${NAMESPACE:-rockylinux}/${IMAGE:-rockylinux}:${TAG:-9-ubi-init}"
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  env:
    PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint